name: wishlist_app
description: A new Flutter project.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.16.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.4
  firebase_auth: ^3.3.6
  firebase_core: ^1.12.0
  hive: ^2.0.5
  hive_flutter: ^1.1.0

dev_dependencies:
  hive_generator: ^1.1.2
  build_runner: ^2.1.7
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.4

flutter:
  generate: true
  uses-material-design: true

  assets:
    - assets/

  
  
  
  

  
  

  
  

  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
